version: '2'
services:
  webapp:
    build:
      context: ./app
    restart: always
    links:
      - mysql
    ports:
      - "80:80"
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=True
      - MYSQL_DATABASE=hashtopolis_db
      - MYSQL_USER=hashtopolis
      - MYSQL_PASSWORD=mysql_password
